name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing App Dependencies
        run: yarn
      - name: Building App
        run: yarn run build
      - name: Install Firebase Tools
        run: yarn global add firebase-tools
      - name: Deploying to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
